services:
  - type: web
    name: node-video-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node ./bin/www
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_HOSTING_URL
        value: https://angular-19-ssr.web.app
      - key: FIREBASE_HOSTING_URL_ALT
        value: https://angular-19-ssr.firebaseapp.com
    autoDeploy: true
